// Generates src/themes.css from scripts/themes.config.mjs.
//   node scripts/build-themes.mjs         write src/themes.css
//   node scripts/build-themes.mjs --check fail if the committed file is stale
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { THEMES } from "./themes.config.mjs";
import {
  contrast,
  hexToRgb,
  hsl,
  lightenUntil,
  over,
  rgbToHex,
  rgbToHsl,
} from "./palette.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "src", "themes.css");

export function derive(theme) {
  const [h] = rgbToHsl(hexToRgb(theme.accent));
  const hue = Math.round(h);
  const bg = theme.bgHue ?? hue;
  const void_ = hsl(bg, 34, 6.5);
  const ink = hsl(bg, 30, 10.5);
  const slate = hsl(bg, 27, 15);
  const paper = hsl(bg, 34, 94);
  const mist = rgbToHex(over(paper, slate, 0.74)); // opaque, so contrast is exact
  const hairline = `${rgbToHex(over(paper, void_, 0.18))}`;
  const accentText = lightenUntil(theme.accent, slate, 6);
  const btnFg = hsl(bg, 40, 6);
  const btnBg = lightenUntil(theme.accent, btnFg, 6.2);
  const btnHover = rgbToHex(over("#ffffff", btnBg, 0.14));
  const heading = hsl(bg, 45, 97);
  const wash = hsl(bg, 36, 9.5);
  return {
    hue,
    void_,
    ink,
    slate,
    paper,
    mist,
    hairline,
    accentText,
    btnFg,
    btnBg,
    btnHover,
    heading,
    wash,
  };
}

export function render() {
  const lines = [
    "/* GENERATED by scripts/build-themes.mjs from scripts/themes.config.mjs. Do not edit by hand.",
    "   Apply with <html data-ggt-theme=\"moss\"> (or any id below). Same fonts and components as the",
    "   default kit; only colour tokens change. Contrast is verified by `npm test`. */",
    "",
  ];
  for (const t of THEMES) {
    const d = derive(t);
    lines.push(
      `[data-ggt-theme="${t.id}"] {`,
      `  /* ${t.name} (${t.tool}) */`,
      `  --ggt-void: ${d.void_};`,
      `  --ggt-ink: ${d.ink};`,
      `  --ggt-slate: ${d.slate};`,
      `  --ggt-wash: ${d.wash};`,
      `  --ggt-hairline: ${d.hairline};`,
      `  --ggt-paper: ${d.paper};`,
      `  --ggt-mist: ${d.mist};`,
      `  --ggt-heading: ${d.heading};`,
      `  --ggt-accent: ${t.accent};`,
      `  --ggt-accent-text: ${d.accentText};`,
      `  --ggt-link: ${d.accentText};`,
      `  --ggt-btn-bg: ${d.btnBg};`,
      `  --ggt-btn-bg-hover: ${d.btnHover};`,
      `  --ggt-btn-fg: ${d.btnFg};`,
      "}",
      ""
    );
  }
  return lines.join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const css = render();
  if (process.argv.includes("--check")) {
    const cur = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
    if (cur !== css) {
      console.error("src/themes.css is stale. Run: node scripts/build-themes.mjs");
      process.exit(1);
    }
    console.log("src/themes.css is up to date.");
  } else {
    fs.writeFileSync(out, css);
    console.log(`wrote ${path.relative(root, out)} (${THEMES.length} themes)`);
  }
}
